In [2]:
import pandas as pd

In [2]:
df = pd.read_csv("dataset/dataset_01.csv")

In [3]:
df = df.sample(frac=1)
df.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
166,167,1,toyota corolla tercel,gas,std,two,hatchback,rwd,front,94.5,...,98,mpfi,3.24,3.08,9.4,112,6600,26,29,9538.0
129,130,1,porsche cayenne,gas,std,two,hatchback,rwd,front,98.4,...,203,mpfi,3.94,3.11,10.0,288,5750,17,28,31400.5
48,49,0,jaguar xf,gas,std,four,sedan,rwd,front,113.0,...,258,mpfi,3.63,4.17,8.1,176,4750,15,19,35550.0
42,43,1,honda civic (auto),gas,std,two,sedan,fwd,front,96.5,...,110,2bbl,3.15,3.58,9.1,100,5500,25,31,10345.0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [4]:
split_ratio = int(df.shape[0] * .95)
split_ratio

194

In [5]:
df_train = df.iloc[:split_ratio, :]
df_inferences = df.iloc[split_ratio:, :]

df_train.shape, df_inferences.shape

((194, 26), (11, 26))

In [6]:
df_train.to_csv("dataset_01_train")
df_inferences[df_inferences.columns[~df_inferences.columns.isin(["price"])]].to_csv("dataset_01_inferences_X")
df_inferences[["price", "car_ID"]].to_csv("dataset_01_inferences_y")

In [9]:
X = pd.read_csv("dataset/regression/dataset_01_inferences_X")
y = pd.read_csv("dataset/regression/dataset_01_inferences_y")

In [12]:
X

,Unnamed: 0,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,...,cylindernumber,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg
0,77,78,2,mitsubishi lancer,gas,std,two,hatchback,fwd,front,...,four,92,2bbl,2.97,3.23,9.4,68,5500,31,38
1,69,70,0,buick century,diesel,turbo,two,hardtop,rwd,front,...,five,183,idi,3.58,3.64,21.5,123,4350,22,25
2,30,31,2,honda civic,gas,std,two,hatchback,fwd,front,...,four,92,1bbl,2.91,3.41,9.6,58,4800,49,54
3,172,173,2,toyota cressida,gas,std,two,convertible,rwd,front,...,four,146,mpfi,3.62,3.50,9.3,116,4800,24,30
4,142,143,0,subaru brz,gas,std,four,sedan,fwd,front,...,four,108,2bbl,3.62,2.64,9.5,82,4400,28,33
5,144,145,0,subaru r1,gas,std,four,sedan,4wd,front,...,four,108,2bbl,3.62,2.64,9.0,82,4800,24,25
6,37,38,0,honda accord,gas,std,two,hatchback,fwd,front,...,four,110,1bbl,3.15,3.58,9.0,86,5800,27,33
7,2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,...,six,152,mpfi,2.68,3.47,9.0,154,5000,19,26
8,153,154,0,toyota corona hardtop,gas,std,four,wagon,fwd,front,...,four,92,2bbl,3.05,3.03,9.0,62,4800,31,37
9,120,121,1,plymouth fury iii,gas,std,four,hatchback,fwd,front,...,four,90,2bbl,2.97,3.23,9.4,68,5500,31,38
10,170,171,2,toyota tercel,gas,std,two,hardtop,rwd,front,...,four,146,mpfi,3.62,3.50,9.3,116,4800,24,30